-- Seed Data for Photography Studio Portfolio
-- Run this after schema.sql

-- Insert admin accounts (passwords are hashed using bcrypt)
-- Admin 1: osemclicks@gmail.com / heroes.verse57
-- Admin 2: karthikbillava1107@gmail.com / heroes.verse58
INSERT INTO `admins` (`email`, `password`, `name`) VALUES
('osemclicks@gmail.com', '$2y$10$YourHashedPasswordHere1', 'Osem Clicks Admin'),
('karthikbillava1107@gmail.com', '$2y$10$YourHashedPasswordHere2', 'Karthik Billava');

-- Note: The actual password hashes will be generated by the PHP seed script

-- Insert categories
INSERT INTO `categories` (`name`, `slug`) VALUES
('Nature', 'nature'),
('Wild Life', 'wild'),
('Portraits', 'portraits'),
('Monuments', 'monuments');

-- Insert portfolio items (migrating from existing static HTML)
INSERT INTO `portfolio` (`title`, `image_path`, `category_id`, `description`) VALUES
-- Nature category (id: 1)
('Sunset Serenity', 'images/Nature/1.JPG', 1, 'A beautiful sunset capturing nature\'s palette'),
('Morning Dew', 'images/Nature/2.jpg', 1, 'Fresh morning dew on leaves'),
('Mountain Vista', 'images/Nature/9.jpg', 1, 'Majestic mountain landscape'),
('Forest Path', 'images/Nature/3.jpg', 1, 'Peaceful forest trail'),
('Ocean Waves', 'images/Nature/4.jpg', 1, 'Crashing waves at the shore'),
('Flower Bloom', 'images/Nature/5.jpg', 1, 'Delicate flower in full bloom'),
('River Flow', 'images/Nature/6.JPG', 1, 'Gentle river flowing through nature'),
('Sky Colors', 'images/Nature/14.JPG', 1, 'Vibrant sky at golden hour'),
('Landscape Beauty', 'images/Nature/15.jpg', 1, 'Breathtaking natural landscape'),

-- Wildlife category (id: 2)
('Bird in Flight', 'images/Wildlife/9.jpg', 2, 'Captured mid-flight moment'),
('Wild Creature', 'images/Wildlife/1.JPG', 2, 'Wildlife in natural habitat'),
('Nature\'s Hunter', 'images/Wildlife/10.jpg', 2, 'Predator in the wild'),
('Winged Beauty', 'images/Wildlife/2.jpg', 2, 'Beautiful bird portrait'),
('Forest Dweller', 'images/Wildlife/4.jpg', 2, 'Animal in forest setting'),
('Wild Eyes', 'images/Wildlife/6.jpg', 2, 'Close-up wildlife portrait'),
('Untamed Spirit', 'images/Wildlife/7.jpg', 2, 'Wildlife in action'),

-- Portraits category (id: 3)
('Portrait Session', 'images/Portraits/20.jpg', 3, 'Professional portrait photography'),
('Character Study', 'images/Portraits/11.jpg', 3, 'Capturing personality'),
('Expression', 'images/Portraits/7.JPG', 3, 'Emotional portrait'),
('Studio Portrait', 'images/Portraits/2.JPG', 3, 'Classic studio setup'),
('Natural Light', 'images/Portraits/3.jpg', 3, 'Portrait with natural lighting'),
('Candid Moment', 'images/Portraits/4.JPG', 3, 'Genuine candid expression'),
('Portrait Art', 'images/Portraits/8.JPG', 3, 'Artistic portrait composition'),
('Face Study', 'images/Portraits/9.JPG', 3, 'Detailed facial portrait'),
('Personality', 'images/Portraits/10.jpg', 3, 'Capturing character'),
('Style Portrait', 'images/Portraits/12.jpg', 3, 'Stylized portrait photography'),
('Mood Portrait', 'images/Portraits/13.jpg', 3, 'Atmospheric portrait'),
('Contemporary', 'images/Portraits/14.jpg', 3, 'Modern portrait style'),
('Classic Beauty', 'images/Portraits/15.jpg', 3, 'Timeless portrait'),
('Bold Portrait', 'images/Portraits/16.jpg', 3, 'Striking portrait composition'),
('Elegant', 'images/Portraits/17.jpg', 3, 'Elegant portrait photography'),
('Frame Study', 'images/Portraits/18.jpg', 3, 'Creative framing'),
('Portrait Series', 'images/Portraits/21.jpg', 3, 'Part of portrait collection'),

-- Monuments category (id: 4)
('Mysore Palace', 'images/Monuments/1.jpg', 4, 'Historic Mysore Palace'),
('Yaavdo Building', 'images/Monuments/2.JPG', 4, 'Architectural beauty');

-- Insert page content for CMS
INSERT INTO `page_content` (`page`, `section`, `content`) VALUES
-- About page
('about', 'who_we_are', 'We are a professional visual services studio based in Kundapura, Karnataka. We provide high-quality production and post-production services for individuals, brands, businesses, events, and content creators.\n\nOur expertise includes cinematic shoots, promotional videos, photography projects, and editing services. At Osem Clicks, we don\'t just capture moments—we transform ideas into visually compelling stories.'),

('about', 'our_story', 'Osem Clicks was founded by Keerthan B, beginning as a passion project with a camera and a vision.\n\nOver time, it has grown into a trusted creative studio known for reliability, creativity, and attention to detail.\n\nWe currently provide customized solutions in:\n• Filming\n• Photography\n• Editing\n• Visual content production\n\nCatering to individual creators, small businesses, and large organizations.'),

-- Services page
('services', 'event_shoots', 'Professional photo/video coverage for corporate events, parties, and gatherings. We capture every important moment with precision and creativity.'),

('services', 'product_shoots', 'High-quality product photography & videos for social media, e-commerce, and marketing campaigns. Make your products stand out with professional visuals.'),

('services', 'content_creation', 'Full shooting + editing solutions for content creators (Instagram, YouTube, etc.). From concept to final edit, we\'ve got you covered.'),

('services', 'brand_corporate', 'Visual content for marketing campaigns, product launches, brand promotions, etc. Elevate your brand with professional corporate visuals.'),

('services', 'editing_post', 'Color correction, retouching, highlight reels, montage videos, and complete post-production work. Transform your raw footage into polished masterpieces.'),

('services', 'cinematic', 'Cinematic short films, BTS coverage, and unique storytelling visuals. We bring cinematic quality to your projects.'),

-- Home page
('home', 'hero_title', 'Excellence In Every Frame'),
('home', 'hero_subtitle', 'Photography, Videography and editing services by Osem Clicks'),

-- Contact page
('contact', 'email', 'osemclicks@gmail.com'),
('contact', 'phone', '+91 63646 20304'),
('contact', 'location', 'Osem Clicks Studio, Kundapura, Udupi, Karnataka');

-- Insert FAQs
INSERT INTO `faqs` (`question`, `answer`, `display_order`) VALUES
('What services do you offer?', 'We offer a comprehensive range of visual services including photography, videography, editing, and post-production for events, products, content creation, brand campaigns, and specialized cinematic projects.', 1),

('Where are you located?', 'We are based in Kundapura, Udupi, Karnataka. However, we are available for shoots across Karnataka and beyond.', 2),

('How do I book a session?', 'You can book a session by filling out our contact form, calling us at +91 63646 20304, or emailing us at osemclicks@gmail.com. We\'ll discuss your requirements and schedule accordingly.', 3),

('What are your rates?', 'Our rates vary depending on the type of service, duration, and specific requirements. Please contact us with your project details for a customized quote.', 4),

('Do you provide editing services only?', 'Yes! We offer standalone editing and post-production services. If you have raw footage or photos that need professional editing, we can help.', 5),

('What equipment do you use?', 'We use professional-grade equipment including the iPhone 15 for mobile photography, along with professional cameras, lenses, stabilizers, and editing software to ensure top-quality results.', 6),

('How long does it take to receive final deliverables?', 'Delivery time depends on the project scope. Typically, edited photos are delivered within 5-7 days, and videos within 10-14 days. Rush delivery options are available upon request.', 7),

('Can I request revisions?', 'Absolutely! We offer revision rounds to ensure you\'re completely satisfied with the final product. The number of revisions depends on the package you choose.', 8);

-- Insert gears (migrating from footer)
INSERT INTO `gears` (`name`, `affiliate_link`, `display_order`) VALUES
('Mobile Holder', 'https://amzn.to/3IJGqYq', 1),
('Apple iPhone 15 (128 GB)', 'https://amzn.to/490PSkH', 2),
('SanDisk 1TB Portable SSD', 'https://amzn.to/4ofqEmT', 3);

-- Insert sample blog posts
INSERT INTO `blogs` (`title`, `cover_image`, `content`, `excerpt`) VALUES
('Welcome to Osem Clicks', 'uploads/blogs/welcome-cover.jpg', 
'<h2>Starting Our Journey</h2><p>Welcome to the official Osem Clicks blog! We\'re excited to share our photography journey, tips, and behind-the-scenes stories with you.</p><p>Photography is more than just clicking pictures—it\'s about capturing emotions, telling stories, and preserving memories. At Osem Clicks, we believe every frame has a story to tell.</p><h3>What to Expect</h3><ul><li>Photography tips and techniques</li><li>Behind-the-scenes from our shoots</li><li>Equipment reviews</li><li>Client success stories</li><li>Industry insights</li></ul><p>Stay tuned for more exciting content!</p>', 
'Welcome to the official Osem Clicks blog! We\'re excited to share our photography journey, tips, and stories with you.'),

('5 Tips for Better Portrait Photography', 'uploads/blogs/portrait-tips-cover.jpg',
'<h2>Master the Art of Portrait Photography</h2><p>Portrait photography is one of the most rewarding genres. Here are 5 essential tips to improve your portrait work:</p><h3>1. Focus on the Eyes</h3><p>The eyes are the window to the soul. Always ensure the eyes are sharp and in focus. This creates an immediate connection between the subject and the viewer.</p><h3>2. Use Natural Light When Possible</h3><p>Natural light can create beautiful, soft portraits. Try shooting during golden hour (sunrise or sunset) for warm, flattering light.</p><h3>3. Mind Your Background</h3><p>A cluttered background distracts from your subject. Look for clean, simple backgrounds or use a wide aperture to blur the background.</p><h3>4. Connect with Your Subject</h3><p>Talk to your subject, make them comfortable, and capture genuine expressions. The best portraits show authentic emotion.</p><h3>5. Experiment with Angles</h3><p>Don\'t just shoot at eye level. Try different angles—shoot from above, below, or from the side to create more dynamic portraits.</p><p>Practice these tips and watch your portrait photography improve dramatically!</p>',
'Master portrait photography with these 5 essential tips for capturing stunning, professional-quality portraits.');
